name: eMOSIAC
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - wandb=0.16.2
  - pyyaml=6.0.1
  - numpy=1.23.5
  - pandas=1.5.3
  - seaborn
  - xgboost=2.0.3
  - scipy=1.10.0
  - pip=23.0
  - rdkit   
  - cudatoolkit=11.3 
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - torch==1.12.1+cu113
      - torchvision==0.13.1+cu113
      - torchaudio==0.12.1+cu113
      - pyg_lib
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv
      - torch-geometric==2.2.0
      - -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
