name: eMOSIAC
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - wandb=0.16.2
  - pyyaml=6.0.1
  - numpy=1.23.5
  - pandas=1.5.3
  - seaborn
  - xgboost=2.0.3
  - scipy=1.10.0
  - pip=23.0
